version: "3.9"

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: nawy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - nawy-db-data:/var/lib/postgresql/data
    networks:
      - nawy-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: nawy
    volumes:
      - server-node-modules:/app/node_modules
      - ./backend:/app
    networks:
      - nawy-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: npm run dev
    restart: always
    depends_on:
      - backend
    ports:
      - 4000:3000
    environment:
      NEXT_PUBLIC_API_BASE_URL: "http://localhost:3000"
    volumes:
      - ./web:/app
      - web-node-modules:/app/node_modules
    networks:
      - nawy-network

volumes:
  nawy-db-data:
  server-node-modules:
  web-node-modules:

networks:
  nawy-network:
    name: nawy-network
